### ISSUE TITLE
Pass parameters to flows

### ISSUE THREAD

**Issue by naicigam** [SalesforceFoundation/CumulusCI#315]
I am trying to run the `ci_beta` flow, but trying to pass a specific package version to the `install_managed_beta` task.

I tried the `-o ` parameter, but does not work at a workflow level, so the option that comes to my mind is running task by task and pass the version using the `cci task run install_managed_beta -o version 1.1b` command line.

Is there another way of doing this that allows me to take advantage of future updates to the flows?

Thanks!
Juan M.

**Comment by jlantz** [comment]
That's definitely an enhancement to flows that I'd like to see, but at the moment passing options to flows isn't possible.  The ci_beta flow looks up the latest release from Github Releases for the repo and installs that version.

The code for flows is actually pretty simple so I think this wouldn't be too hard to add:
https://github.com/SalesforceFoundation/CumulusCI/blob/master/cumulusci/core/flows.py

**Comment by cdcarter** [comment]
It's relatively quick to override a single flow task definition in local YAML:

```
    ci_beta:
        tasks:
            4:
                task: install_managed_beta
                options:
                    version: 1.1b
```

This isn't ideal, but its a quick git stash pop...
