### ISSUE TITLE
Share managed and unmanaged package

### ISSUE THREAD

**Issue by naicigam** [SalesforceFoundation/CumulusCI#331]
Hi! I would like to ask you a question about sharing a managed an and unmanaged package in the same codebase.

I have two folders `src` and `src_unmanaged`, each with its own `package.xml` and I would like to deploy both to the same package org that has a managed and an unmanaged package.

I am able to deploy the managed package easily by calling `cci flow run ci_master --org package`, but I can't make the second part work. 

So far, I tried replicating the same flow using the unmanaged counterparts like this:

```
flows:
    deploy_unmanaged_package:
        tasks:
            1:
                task: deploy_pre
            2:
                task: update_dependencies
                options:
                    path: src_unmanaged
                    package: My Unmanaged Package
            3:
                task: uninstall_packaged_incremental
                ignore_failure: true
                options: 
                    path: src_unmanaged
                    package: My Unmanaged Package
            4: 
                task: update_package_xml
                options: 
                    path: src_unmanaged
                    package: My Unmanaged Package
            5: 
                task: create_unmanaged_ee_src
                options: 
                    path: src_unmanaged
                    package: My Unmanaged Package
            6: 
                task: deploy
                options: 
                    path: src_unmanaged
                    package: My Unmanaged Package
            7: 
                task: revert_unmanaged_ee_src
                options: 
                    path: src_unmanaged
                    package: My Unmanaged Package
            8: 
                task: uninstall_packaged_incremental
                options: 
                    path: src_unmanaged
                    package: My Unmanaged Package
            9:
                task: update_admin_profile
```
But when I go to the unmanaged package in my org, it is still empty.

Could you please point me in the right direction?

Thanks!
