### ISSUE TITLE
Allow dependencies to refer to other CumulusCI configured repositories

### ISSUE THREAD

**Issue by jlantz** [SalesforceFoundation/CumulusCI#332]
Currently an extension package project needs to maintain its own list of dependencies manually.  This can become challenging if extending another extension package.

Consider the following structure for three managed package repositories:

RepoA - no dependencies, latest is 1.1
RepoB - requires RepoA, latest is 1.2
RepoC - requires RepoB, latest is 1.3

The cumulusci.yml files should look like:

**RepoA**
```
project:
    package:
        namespace: RepoA
```
**RepoB**
```
project:
    package:
        namespace: RepoB
    dependencies:
        - github: https://github.com/TestOwner/RepoA
```

**RepoC**
```
project:
    package:
        namespace: RepoC
    dependencies:
        - github: https://github.com/TestOwner/RepoB

```

When you run `cci task run update_dependencies` from within RepoC, the following should happen:
- Github is queried to fetch the `cumulusci.yml` file from RepoB
- Github is queried to fetch the `cumulusci.yml` file from RepoA due to the reference in RepoB's `cumulusci.yml`
- The processed dependency map for RepoC should be:
```
- namespace: RepoB
  version: 1.2
  dependencies
    - namespace: RepoA
      version: 1.1
```
